build:
    nodes:
        analysis:
            dependencies:
                before:
                    - git clone ssh://git@gitlab.netinventors.de:2202/shopware/plugins/NetiFoundation.git
            environment:
                php:
                    version: 5.6.16

filter:
    dependency_paths:
        - "NetiFoundation/*"

checks:
    php:
        code_rating: true
        duplication: true